---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-vpn
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 4314
      protocol: UDP
    - port: 4314
      protocol: TCP
    to:
    - cidr: 0.0.0.0/0
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-dns
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-https
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-http
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-ntp
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 123
---
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-to-istio
  namespace: firewall
spec:
  egress:
  - to:
    - cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 8443
